import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';
import './globals.css';
import { ReactQueryProvider } from '@/lib/ReactQueryProvider';
import { Toaster } from 'react-hot-toast';

const archivo = Archivo({
  variable: '--font-archivo',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // sesuaikan kebutuhanmu
  display: 'swap',
});
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: 'blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} antialiased font-sans `}>
        <NextTopLoader />
        <Toaster />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
